import type { GetServerSideProps, NextPage } from 'next'
import Head from 'next/head'
import Banner from '../components/Banner'
import { Header } from '../components/Header'
import FeaturingProductList from '../components/FeaturingProductsList'

export type featuringProps= {
  featuringProducts: {
    id: number,
    title: string,
    price: number,
    description: string,
    category: string,
    image: string,
    rating: {
      rate: number,
      count: number
    }
  }[]
}
const Home: NextPage = ({featuringProducts}: featuringProps) => {
  return (
    <div className="bg-gray-lightest">
      <Head>
        <title>Ecommerce</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className='max-w-screen-2xl mx-auto'> 
        <Banner />
        <FeaturingProductList featuringProducts={featuringProducts} />
      </main>
    </div>
  )
}

export default Home

export const getServerSideProps: GetServerSideProps = async (context) => {
  const featuringProducts = await fetch('https://fakestoreapi.com/products?limit=4')
  .then(response => response.json())
  console.log(featuringProducts)
  return {
    props: {
      featuringProducts
    }
  }
}
